# Generated by Django 6.0.7 on 2026-07-25 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_price_enrollment_payment_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at'], 'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='liveclass',
            options={'ordering': ['scheduled_time'], 'verbose_name': 'Live Class', 'verbose_name_plural': 'Live Classes'},
        ),
        migrations.AlterModelOptions(
            name='liveclassattendance',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Live Class Attendance', 'verbose_name_plural': 'Live Class Attendances'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-created_at'], 'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name': 'Module', 'verbose_name_plural': 'Modules'},
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the course content.', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Course cost in the default currency.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='The public-facing title of the course.', max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='last_watched_lesson',
            field=models.ForeignKey(blank=True, help_text='Most recent lesson the student has watched; used to restore progress.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.lesson'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=15),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(help_text='The module this lesson belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.module'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within the module (ascending).'),
        ),
        migrations.AlterField(
            model_name='liveclass',
            name='scheduled_time',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='lesson',
            field=models.ForeignKey(help_text='The lesson this media belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='lms.lesson'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('notes', 'Notes (PDF)')], help_text='The type of media content.', max_length=10),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, help_text='Optional display title for this media item.', max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(help_text='The course this module belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='lms.course'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within the course (ascending).'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'course'], name='lms_enrollm_user_id_9dafc4_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='lms_lesson_module__2de88e_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['lesson', 'media_type'], name='lms_media_lesson__754a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='lms_module_course__053625_idx'),
        ),
    ]
