# Generated by Django 6.0.7 on 2026-07-25 09:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_course_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid.', max_digits=10)),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('upi', 'UPI'), ('bank', 'Bank Transfer'), ('cash', 'Cash'), ('card', 'Card'), ('other', 'Other')], default='upi', max_length=20)),
                ('reference_id', models.CharField(blank=True, help_text='Transaction ID or reference number.', max_length=255)),
                ('remarks', models.TextField(blank=True, help_text='Any additional notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(help_text='The enrollment this payment is for.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='lms.enrollment')),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['enrollment', 'payment_date'], name='lms_payment_enrollm_17b423_idx')],
            },
        ),
    ]
