# Generated by Django 6.0.7 on 2026-07-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_paymentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='course_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Agreed course fee for this student (may differ from the listed course price).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Legacy: initial payment amount recorded at enrollment.', max_digits=10),
        ),
    ]
