# Generated by Django 6.0.7 on 2026-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_enrollment_course_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveclass',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the live class.', max_length=15),
        ),
    ]
