# Generated by Django 6.0.7 on 2026-08-23

import lms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_liveclass_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="drive_url",
            field=models.URLField(
                blank=True,
                help_text="Paste a Google Drive file sharing link. Set the file access to 'Anyone with the link' so enrolled students can view it.",
                null=True,
                validators=[lms.models.validate_google_drive_url],
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Legacy uploaded file. New media must use the Google Drive link above.",
                upload_to="lms_media/",
            ),
        ),
    ]
