"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
# pyrefly: ignore [missing-import]
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    CORS_ALLOW_ALL_ORIGINS=(bool, False),
    EMAIL_USE_TLS=(bool, True),
)
# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'unfold',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # Local apps
    'users',
    'lms',
]

# django-debug-toolbar — only loaded in local development
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']

    INTERNAL_IPS = [
        '127.0.0.1',
        'localhost',
    ]

# ─── Django Unfold Admin Theme ───────────────────
from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    'SITE_TITLE': 'Kryon LMS',
    'SITE_HEADER': 'Kryon LMS',
    'SITE_URL': '/',
    'SITE_LOGO': lambda request: static('admin/img/kryon-logo.png'),
    'SITE_LOGO_ALT': 'Kryon LMS',
    'SITE_SYMBOL': 'school',
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
    'DASHBOARD_CALLBACK': 'core.dashboard.dashboard_callback',
    'COLORS': {
        'primary': {
            '50': '#eff6ff',
            '100': '#dbeafe',
            '200': '#bfdbfe',
            '300': '#93c5fd',
            '400': '#60a5fa',
            '500': '#3b82f6',
            '600': '#2563eb',
            '700': '#1d4ed8',
            '800': '#1e40af',
            '900': '#1e3a8a',
            '950': '#172554',
        },
    },
    'EXTENSIONS': {
        'modeltranslation': {
            'flags': {},
        },
    },
    'SIDEBAR': {
        'show_search': True,
        'show_all_applications': True,
        'navigation': [
            {
                'title': 'Dashboard',
                'separator': False,
                'items': [
                    {
                        'title': 'Overview',
                        'icon': 'dashboard',
                        'link': reverse_lazy('admin:index'),
                        'permission': lambda request: request.user.is_staff,
                    },
                ],
            },
            {
                'title': 'LMS',
                'separator': True,
                'items': [
                    {
                        'title': 'Courses',
                        'icon': 'menu_book',
                        'link': reverse_lazy('admin:lms_course_changelist'),
                        'permission': lambda request: request.user.has_perm('lms.view_course'),
                    },
                    {
                        'title': 'Modules',
                        'icon': 'layers',
                        'link': reverse_lazy('admin:lms_module_changelist'),
                        'permission': lambda request: request.user.has_perm('lms.view_module'),
                    },
                    {
                        'title': 'Lessons',
                        'icon': 'play_circle',
                        'link': reverse_lazy('admin:lms_lesson_changelist'),
                        'permission': lambda request: request.user.has_perm('lms.view_lesson'),
                    },
                    {
                        'title': 'Media',
                        'icon': 'perm_media',
                        'link': reverse_lazy('admin:lms_media_changelist'),
                        'permission': lambda request: request.user.has_perm('lms.view_media'),
                    },
                    {
                        'title': 'Enrollments',
                        'icon': 'how_to_reg',
                        'link': reverse_lazy('admin:lms_enrollment_changelist'),
                        'permission': lambda request: request.user.has_perm('lms.view_enrollment'),
                    },
                    {
                        'title': 'Live Classes',
                        'icon': 'videocam',
                        'link': reverse_lazy('admin:lms_liveclass_changelist'),
                        'permission': lambda request: request.user.has_perm('lms.view_liveclass'),
                    },
                ],
            },
            {
                'title': 'Users',
                'separator': True,
                'items': [
                    {
                        'title': 'Students',
                        'icon': 'school',
                        'link': reverse_lazy('admin:users_student_changelist'),
                        'permission': lambda request: request.user.has_perm('users.view_student'),
                    },
                    {
                        'title': 'Staff',
                        'icon': 'shield_person',
                        'link': reverse_lazy('admin:users_staff_changelist'),
                        'permission': lambda request: request.user.has_perm('users.view_staff'),
                    },
                    {
                        'title': 'Inquiries',
                        'icon': 'question_answer',
                        'link': reverse_lazy('admin:users_inquiry_changelist'),
                        'permission': lambda request: request.user.has_perm('users.view_inquiry'),
                    },
                    {
                        'title': 'OTPs',
                        'icon': 'key',
                        'link': reverse_lazy('admin:users_otp_changelist'),
                        'permission': lambda request: request.user.has_perm('users.view_otp'),
                    },
                    {
                        'title': 'Groups',
                        'icon': 'group',
                        'link': reverse_lazy('admin:auth_group_changelist'),
                        'permission': lambda request: request.user.has_perm('auth.view_group'),
                    },
                ],
            },
        ],
    },
    'TABS': [
        {
            'models': ['users.student', 'users.staff', 'users.inquiry', 'users.otp', 'auth.group'],
            'items': [
                {'title': 'Students', 'link': reverse_lazy('admin:users_student_changelist')},
                {'title': 'Staff', 'link': reverse_lazy('admin:users_staff_changelist')},
                {'title': 'Inquiries', 'link': reverse_lazy('admin:users_inquiry_changelist')},
                {'title': 'OTPs', 'link': reverse_lazy('admin:users_otp_changelist')},
                {'title': 'Groups', 'link': reverse_lazy('admin:auth_group_changelist')},
            ],
        },
        {
            'models': ['lms.course', 'lms.module', 'lms.lesson', 'lms.media', 'lms.enrollment', 'lms.liveclass'],
            'items': [
                {'title': 'Courses', 'link': reverse_lazy('admin:lms_course_changelist')},
                {'title': 'Modules', 'link': reverse_lazy('admin:lms_module_changelist')},
                {'title': 'Lessons', 'link': reverse_lazy('admin:lms_lesson_changelist')},
                {'title': 'Media', 'link': reverse_lazy('admin:lms_media_changelist')},
                {'title': 'Enrollments', 'link': reverse_lazy('admin:lms_enrollment_changelist')},
                {'title': 'Live Classes', 'link': reverse_lazy('admin:lms_liveclass_changelist')},
            ],
        },
    ],
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Insert debug toolbar middleware only in development
if DEBUG:
    MIDDLEWARE.insert(2, 'debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='5432'),
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'kryon-lms-cache',
    }
}

AUTH_USER_MODEL = 'users.User'

# CORS and CSRF
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=DEBUG)
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    'http://localhost:5173',
    'http://127.0.0.1:5173',
])
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:5173',
    'http://127.0.0.1:5173',
])

# Allow CSRF cookie to be read by JavaScript (needed for admin multipart forms)
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_HTTPONLY = True

# Email (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

# DRF configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # Disable the Browsable API in production (only enables it in DEBUG mode)
    'DEFAULT_RENDERER_CLASSES': (
        ['rest_framework.renderers.JSONRenderer', 'rest_framework.renderers.BrowsableAPIRenderer']
        if DEBUG else
        ['rest_framework.renderers.JSONRenderer']
    ),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Default primary key type ──────────────────────────────────────────────────
# Explicitly set to avoid Django's system check warning.
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Production security headers ───────────────────────────────────────────────
# These are no-ops in local dev (DEBUG=True) and activate in production.
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000          # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ── Logging ───────────────────────────────────────────────────────────────────
import logging

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'lms': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'users': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
    },
}
